# This is a basic workflow to help you get started with Actions

name: URL2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '00 */2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-job:
    name: Max job
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/setup-python@v4 #python环境
      with:
        python-version: '3.x'       #python 3.x
        # cache: 'pip'    
    - name: Timezone #UTC+0 → UTC+8
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.test }}
        submodules: 'true'
        ssh-key: ${{  secrets.action  }}
        repository: UsersHeli/speed
        path: speed
    - name: chech dir
      run:  |
         echo `pwd`/speed
         echo `ls ./speed`
    - name: run
      run: |
         cd speed && sh workflow.sh `pwd`
    - uses: actions/checkout@v3
      with: 
        path: test
    - name: cp
      run: |
         cp ./speed/Eternity.yaml ./test/url1.yaml
         cd ./test
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
         git pull origin main
         git add ./url1.yaml
         git commit -m "$(date '+%Y-%m-%d %H:%M:%S')更新"
         git push origin main

  # # This workflow contains a single job called "build"
  # build:
  #   name: test
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - name: run node
  #       uses: actions/checkout@v3
  #       with: 
  #         ssh-key: ${{  secrets.action  }}
  #         token: ${{  secrets.PERSONAL_TOKEN  }}
  #         repository: UsersHeli/ituse
  #         path: ./github/workflows/Nodes.yaml
  #     # # Runs a single command using the runners shell
  #     # - name: Run a one-line script
  #     #   run: echo Hello, world!

  #     # # Runs a set of commands using the runners shell
  #     # - name: Run a multi-line script
  #     #   run: |
  #     #     echo Add other actions to build,
  #     #     echo test, and deploy your project.
